name: "Auto-merge PR"

on:
  pull_request_target:
    types: [labeled]

permissions:
  {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Install the dependencies
        run: npm ci --include=prod

      - name: Update
        run: nix develop .#ci -c ./update.bash

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add npm-hash.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: Updated the npm hash"
            git push
          fi

  merge:
    needs: update

    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.pull_request.user.login == 'dependabot[bot]'

    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    steps:
      - uses: actions/create-github-app-token@7989d206df2ffdd9fc88b0eb6d2f0eebee835fd6 # v3.1.1
        id: generate-token
        with:
          app-id: ${{ secrets.CREATE_PR_APP_ID }}
          private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          github-token: ${{ github.token }}

      - name: Merge
        if: |
          steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'
          || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor'
          || steps.dependabot-metadata.outputs.package-ecosystem == 'nix'
        run: |
          gh pr merge "$PR_URL" --delete-branch --merge --auto
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
