name: Lint JavaScript code

on:
  pull_request:
    paths-ignore:
      - README.*

  push:
    branches:
      - master
    paths-ignore:
      - README.*

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  npm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint
